version: '3.7'

services:
  web:
    build: .
    command: uvicorn application.base:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    env_file:
      - .env
    ports:
      - 27017:27017
